### ISSUE TITLE
OnComplete with looping video

### ISSUE THREAD

**Issue by gaborpapp** [axjxwright/AX-MediaPlayer#8] opened 2022-10-07 12:29 UTC
The OnComplete signal is called when the looping movie reaches the end on macOS, but it is never called on Windows.
I think the macOS behaviour would be preferable.

**Comment by axjxwright** [comment] 2022-10-07 13:10
Unfortunately this is apparently expected behaviour on windows since it's modeled after the HTML5 video spec, which _also_ doesn't fire complete events on loop. I agree with you so I've attempted to emulate the looping event by catching certain tell tale seek events. 

Do you think the `OnComplete` handler should have a `bool isLoop` or something? Or maybe a separate `OnLoop` signal could also be fired?

Anyway if you could let me know if this update fixes your problem and any thoughts you might have about the above that'd be great. Thanks for reporting this problem

A

**Comment by gaborpapp** [comment] 2022-10-07 13:35
Thanks for the super quick fix. It works nicely.

I think I'm happy with the behaviour of `OnComplete` like this, since we know if the video is looping or not. Maybe the naming can be more clear to show the movie has reached the end, but can be still playing, while `OnComplete` might suggest that it is stopped playing. Just a suggestion, it might not worth it to break existing code.

**Comment by axjxwright** [comment] 2022-10-07 13:37
I think I might add a separate `OnLooped` event at some stage so that it doesn't break any existing code as you say. Closing this for now then. Thanks mate

**Closed by axjxwright** 2022-10-07 13:37 UTC
Labels: ready to test
